import { Metadata } from "next";
import React from 'react';
import Contact from "./components/contact";


export const metadata: Metadata = {
    title: 'About Services',
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <div>
            <Contact />
        </div>
    );
}
