import React from 'react';
import Hero from './components/hero';
import Features from './components/features';
import 'next';
import { Metadata } from 'next';



export const metadata: Metadata = {
    title: 'About Services',
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <div>
            <Hero />
            <Features />
        </div>
    );
}
