import React from 'react';
import Hero from './components/hero';
import Features from './components/features';
import 'next';
import { Metadata } from 'next';
import { Frame, Link } from 'lucide-react';
import { Button } from '@/components/ui/button';



export const metadata: Metadata = {
    title: 'About Services',
    description: "Generated by create next app",
};

export default function Page() {
    return (

        <div>
            <Hero />
            <Features />
        </div>
        /* <Frame id="toolbar-navigation">

            <Button className='mt-4' asChild>
                <Link href='/about'>About page</Link>
            </Button>
        </Frame>
        */

    );
}
