import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { Button } from "@/components/ui/button"; // Button コンポ
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";


const inter = Inter({ subsets: ["latin"] });

const navItems = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
]

export const metadata: Metadata = {
  title: {
    template: "%s | leo",
    default: "leo",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, 'min-h-dvh')}>

      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
      >
        <header className="container h-16 flex items-center border-b justify-between">
          <h1 className="font-bold text-2xl">LEO</h1>
          <ul className="flex gap-4">
            {navItems.map((item) => (
              <li key={item.label}>
                <Button variant="ghost" asChild>
                  <Link href={item.href}>{item.label}</Link>
                </Button>
                </li>
              ))}
          </ul>
        </header>
        <main>{children}</main>

        <footer className="container sticky top-full h-16 flex justify-between items-center border-t">
          <p>&copy; leo</p>

          <ModeToggle />
        </footer>

        </ThemeProvider>
      </body>
    </html>
  );
}
